import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
const OUT = resolve(import.meta.dirname ?? '.', 'seed.sql');
function sq(v: string | number | null | undefined): string {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
}
const NOW = Date.now();
const DAY = 86400000;
const HOUR = 3600000;
let _rng = 0x9e3779b97f4a7c15n;
function rand(): number {
  _rng = (_rng * 6364136223846793005n + 1442695040888963407n) & ((1n << 64n) - 1n);
  return Number((_rng >> 33n) & 0xffffffffn) / 0xffffffff;
}
function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(rand() * arr.length)];
}
function chance(p: number): boolean {
  return rand() < p;
}
function rint(min: number, max: number): number {
  return Math.floor(rand() * (max - min + 1)) + min;
}
function pad(n: number, w = 3): string {
  return String(n).padStart(w, '0');
}
function fmtMoney(n: number): string {
  return new Intl.NumberFormat('en-US', { maximumFractionDigits: 0 }).format(n);
}
type PriceMode = 'fixed' | 'hourly' | 'negotiable' | 'free';
function buildPriceSummary(
  mode: PriceMode,
  min: number | undefined,
  max: number | undefined,
  currency: string,
): string | undefined {
  switch (mode) {
    case 'free':
      return 'Free';
    case 'negotiable':
      return 'Negotiable';
    case 'fixed':
      return min !== undefined ? `${fmtMoney(min)} ${currency}` : undefined;
    case 'hourly':
      if (min !== undefined && max !== undefined && max !== min)
        return `${fmtMoney(min)}–${fmtMoney(max)} ${currency}/hr`;
      if (min !== undefined) return `${fmtMoney(min)} ${currency}/hr`;
      return undefined;
  }
}
type SeedUser = {
  num: number;
  name: string;
  displayName: string;
  email: string;
  telegram: string;
  city: string | null;
  bio: string | null;
  joinedDaysAgo: number;
  image?: string | null;
};
const CITIES = [
  'Almaty',
  'Astana',
  'Shymkent',
  'Karaganda',
  'Aktobe',
  'Pavlodar',
  'Oskemen',
  'Semey',
  'Atyrau',
  'Taraz',
  'Kostanay',
  'Kyzylorda',
];
const PEOPLE: SeedUser[] = [
  {
    num: 1,
    name: 'Aigerim Bekova',
    displayName: 'Aigerim B.',
    email: 'aigerim.bekova@example.com',
    telegram: 'aigerim_b',
    city: 'Almaty',
    bio: 'Math tutor ~6 yrs. Fine with folks who forgot half of school. KZ/RU/EN.',
    joinedDaysAgo: 84,
  },
  {
    num: 2,
    name: 'Nurlan Iskakov',
    displayName: 'Nurlan I.',
    email: 'nurlan.iskakov@example.com',
    telegram: 'nurlan_fix',
    city: 'Astana',
    bio: 'Plumber and small repairs. Same-day visits in Astana.',
    joinedDaysAgo: 78,
  },
  {
    num: 3,
    name: 'Dana Sultan',
    displayName: 'Dana S.',
    email: 'dana.sultan@example.com',
    telegram: 'dana_designs',
    city: 'Almaty',
    bio: 'Brand & UI designer. Cafés, small businesses, side-project landing pages.',
    joinedDaysAgo: 72,
  },
  {
    num: 4,
    name: 'Yerzhan Toleu',
    displayName: 'Yerzhan T.',
    email: 'yerzhan.toleu@example.com',
    telegram: 'yerzhan_translate',
    city: 'Shymkent',
    bio: 'Сертифицированный переводчик KZ↔RU↔EN. Документы, нотариальные.',
    joinedDaysAgo: 70,
  },
  {
    num: 5,
    name: 'Aliya Zhumagulova',
    displayName: 'Aliya Zh.',
    email: 'aliya.zhuma@example.com',
    telegram: 'aliya_english',
    city: 'Almaty',
    bio: 'IELTS, mostly people stuck around B1. First lesson free if we get on.',
    joinedDaysAgo: 66,
  },
  {
    num: 6,
    name: 'Sanzhar Kim',
    displayName: 'Sanzhar K.',
    email: 'sanzhar.kim@example.com',
    telegram: 'sanzhar_dev',
    city: 'Almaty',
    bio: 'Swift/iOS. Small gigs and looking at other people’s diffs.',
    joinedDaysAgo: 60,
  },
  {
    num: 7,
    name: 'Kamila Akhmetova',
    displayName: 'Kamila A.',
    email: 'kamila.akhmetova@example.com',
    telegram: 'kamila_ru',
    city: 'Astana',
    bio: 'Преподаватель русского языка для иностранцев. Онлайн и очно.',
    joinedDaysAgo: 58,
  },
  {
    num: 8,
    name: 'Timur Asanov',
    displayName: 'Timur A.',
    email: 'timur.asanov@example.com',
    telegram: 'timur_photo',
    city: 'Karaganda',
    bio: 'Photographer: weddings, family, products. Sony A7IV + studio.',
    joinedDaysAgo: 55,
  },
  {
    num: 9,
    name: 'Madina Tursunova',
    displayName: 'Madina T.',
    email: 'madina.tursunova@example.com',
    telegram: 'madina_clean',
    city: 'Almaty',
    bio: 'Уборка квартир и офисов. Своя химия. Команда из 2 человек.',
    joinedDaysAgo: 53,
  },
  {
    num: 10,
    name: 'Ruslan Beisembayev',
    displayName: 'Ruslan B.',
    email: 'ruslan.b@example.com',
    telegram: 'ruslan_drive',
    city: 'Astana',
    bio: 'Личный водитель / трансфер аэропорт. Toyota Camry, минивэн под заказ.',
    joinedDaysAgo: 50,
  },
  {
    num: 11,
    name: 'Anel Mukasheva',
    displayName: 'Anel M.',
    email: 'anel.mukasheva@example.com',
    telegram: 'anel_baby',
    city: 'Almaty',
    bio: 'Няня с педагогическим образованием. Стаж 8 лет, рекомендации.',
    joinedDaysAgo: 48,
  },
  {
    num: 12,
    name: 'Daniyar Omarov',
    displayName: 'Daniyar O.',
    email: 'daniyar.omarov@example.com',
    telegram: 'daniyar_web',
    city: 'Pavlodar',
    bio: 'Full-stack web dev. Next.js, Postgres. Сайты под ключ для малого бизнеса.',
    joinedDaysAgo: 46,
  },
  {
    num: 13,
    name: 'Symbat Kassym',
    displayName: 'Symbat K.',
    email: 'symbat.kassym@example.com',
    telegram: 'symbat_design',
    city: 'Astana',
    bio: 'Графический дизайнер. Логотипы, брендинг, упаковка.',
    joinedDaysAgo: 44,
  },
  {
    num: 14,
    name: 'Bauyrzhan Karimov',
    displayName: 'Bauyrzhan K.',
    email: 'bauyrzhan.k@example.com',
    telegram: 'bauyrzhan_move',
    city: 'Almaty',
    bio: 'Газель + грузчики. Квартирные/офисные переезды по Алматы.',
    joinedDaysAgo: 42,
  },
  {
    num: 15,
    name: 'Zarina Bektur',
    displayName: 'Zarina B.',
    email: 'zarina.bektur@example.com',
    telegram: 'zarina_kazakh',
    city: 'Aktobe',
    bio: 'Қазақ тілі мұғалімі. Ересектерге және балаларға. Онлайн сабақтар.',
    joinedDaysAgo: 40,
  },
  {
    num: 16,
    name: 'Alikhan Sariev',
    displayName: 'Alikhan S.',
    email: 'alikhan.sariev@example.com',
    telegram: 'alikhan_guitar',
    city: 'Almaty',
    bio: 'Гитара: уроки для начинающих и средних. Классика, акустика.',
    joinedDaysAgo: 38,
  },
  {
    num: 17,
    name: 'Diana Petrova',
    displayName: 'Diana P.',
    email: 'diana.petrova@example.com',
    telegram: 'diana_yoga',
    city: 'Astana',
    bio: 'Yoga, RYT-200. Private or studio; can come to you if the lift works.',
    joinedDaysAgo: 35,
  },
  {
    num: 18,
    name: 'Erlan Kabikenov',
    displayName: 'Erlan K.',
    email: 'erlan.k@example.com',
    telegram: 'erlan_auto',
    city: 'Karaganda',
    bio: 'Автомеханик, диагностика, ТО. Своё СТО на левом берегу.',
    joinedDaysAgo: 33,
  },
  {
    num: 19,
    name: 'Anna Ivanova',
    displayName: 'Anna I.',
    email: 'anna.ivanova@example.com',
    telegram: 'anna_pets',
    city: 'Almaty',
    bio: 'Walk dogs, sit pets. Took a first-aid course for animals last year.',
    joinedDaysAgo: 30,
  },
  {
    num: 20,
    name: 'Olzhas Begaliev',
    displayName: 'Olzhas B.',
    email: 'olzhas.b@example.com',
    telegram: 'olzhas_chef',
    city: 'Almaty',
    bio: 'Шеф-повар. Готовлю на дом для званых ужинов. Казахская и европейская кухни.',
    joinedDaysAgo: 28,
  },
  {
    num: 21,
    name: 'Gulnara Issagulova',
    displayName: 'Gulnara I.',
    email: 'gulnara.issagulova@example.com',
    telegram: 'gulnara_sew',
    city: 'Shymkent',
    bio: 'Швея, ремонт и подгонка одежды, пошив штор и постельного белья.',
    joinedDaysAgo: 27,
  },
  {
    num: 22,
    name: 'Marat Korkmaz',
    displayName: 'Marat K.',
    email: 'marat.korkmaz@example.com',
    telegram: 'marat_law',
    city: 'Astana',
    bio: 'Юрист: договоры, трудовые споры, регистрация ТОО. Первая консультация бесплатно.',
    joinedDaysAgo: 25,
  },
  {
    num: 23,
    name: 'Aiman Tukenova',
    displayName: 'Aiman T.',
    email: 'aiman.tukenova@example.com',
    telegram: 'aiman_acc',
    city: 'Almaty',
    bio: 'Бухгалтер ИП и ТОО. Отчётность, кадровый учёт, 1С.',
    joinedDaysAgo: 23,
  },
  {
    num: 24,
    name: 'Vladimir Petrov',
    displayName: 'Vladimir P.',
    email: 'vladimir.petrov@example.com',
    telegram: 'volodya_pc',
    city: 'Almaty',
    bio: 'Ремонт ноутбуков и ПК. Чистка, замена термопасты, переустановка ОС.',
    joinedDaysAgo: 22,
  },
  {
    num: 25,
    name: 'Saltanat Bigali',
    displayName: 'Saltanat B.',
    email: 'saltanat.bigali@example.com',
    telegram: 'salta_hair',
    city: 'Astana',
    bio: 'Парикмахер на дому: стрижки, окрашивание, укладки. 7 лет опыта.',
    joinedDaysAgo: 20,
  },
  {
    num: 26,
    name: 'Arman Kozha',
    displayName: 'Arman K.',
    email: 'arman.kozha@example.com',
    telegram: 'arman_fit',
    city: 'Almaty',
    bio: 'PT: strength, boring cardio, stretching. Gym or outside.',
    joinedDaysAgo: 18,
  },
  {
    num: 27,
    name: 'Aizhan Mukatay',
    displayName: 'Aizhan M.',
    email: 'aizhan.mukatay@example.com',
    telegram: 'aizhan_event',
    city: 'Astana',
    bio: 'Организатор мероприятий: тои, корпоративы, дни рождения. Декор и ведущие.',
    joinedDaysAgo: 16,
  },
  {
    num: 28,
    name: 'Beibit Smagulov',
    displayName: 'Beibit S.',
    email: 'beibit.smagulov@example.com',
    telegram: 'beibit_handy',
    city: 'Almaty',
    bio: 'Муж на час: мебель, карнизы, мелкий ремонт. Свой инструмент.',
    joinedDaysAgo: 14,
  },
  {
    num: 29,
    name: 'Nazym Khairulla',
    displayName: 'Nazym Kh.',
    email: 'nazym.kh@example.com',
    telegram: 'nazym_design',
    city: 'Almaty',
    bio: 'Иллюстратор и графический дизайнер. Стикерпаки, мерч, обложки.',
    joinedDaysAgo: 12,
  },
  {
    num: 30,
    name: 'Ilyas Tursyn',
    displayName: 'Ilyas T.',
    email: 'ilyas.tursyn@example.com',
    telegram: 'ilyas_t',
    city: 'Astana',
    bio: 'NU student. Odd jobs + errands around Astana when class allows.',
    joinedDaysAgo: 10,
  },
];
type SeedListingTemplate = {
  authorNum: number;
  kind: 'offer' | 'request';
  title: string;
  description: string;
  category: string;
  tags: string;
  city?: string | null;
  priceMode: PriceMode;
  priceMin?: number;
  priceMax?: number;
  currency?: string;
  status?: 'active' | 'closed' | 'hidden';
  daysAgo: number;
};
const LISTINGS: SeedListingTemplate[] = [
  {
    authorNum: 1,
    kind: 'offer',
    title: 'Репетитор по математике 5–11 класс',
    description:
      'Алгебра, геометрия, ЕНТ: разберём что провисает. Онлайн или в Алмате. Первый раз смотрим бесплатно, без обязаловки.',
    category: 'Tutoring',
    tags: 'math, ent, algebra, geometry, online',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 6000,
    priceMax: 8000,
    daysAgo: 78,
  },
  {
    authorNum: 1,
    kind: 'offer',
    title: 'Подготовка к ЕНТ: математика, интенсив',
    description:
      'Три месяца до экзамена: типовые задачи + домашка. Проверяю, иначе смысла нет.',
    category: 'Tutoring',
    tags: 'ent, math, intensive',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 120000,
    daysAgo: 41,
  },
  {
    authorNum: 1,
    kind: 'request',
    title: 'Ищу няню на 2 часа в день (вторая половина)',
    description: 'Дочке 6 лет. Нужно встретить со школы и побыть до 18:30. Район Орбита, Алматы.',
    category: 'Childcare',
    tags: 'babysitter, after-school, almaty',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 2500,
    daysAgo: 14,
  },
  {
    authorNum: 2,
    kind: 'offer',
    title: 'Сантехник: устраню течь, заменю смеситель',
    description:
      '12 лет по трубам, Астана. На свои косяки даю полгода. Запчасти могу сам привезти.',
    category: 'Repair',
    tags: 'plumber, leak, faucet, astana',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 8000,
    daysAgo: 70,
  },
  {
    authorNum: 2,
    kind: 'offer',
    title: 'Установка стиральной и посудомоечной машин',
    description: 'Подключение к водопроводу и канализации, проверка работы. Чек/накладная.',
    category: 'Repair',
    tags: 'install, washer, dishwasher',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 12000,
    daysAgo: 36,
  },
  {
    authorNum: 2,
    kind: 'offer',
    title: 'Мелкий бытовой ремонт, час работы',
    description: 'Замена кранов, прокладок, труб, унитазов, монтаж полок и карнизов.',
    category: 'Handyman',
    tags: 'handyman, hourly',
    city: 'Astana',
    priceMode: 'hourly',
    priceMin: 5000,
    daysAgo: 9,
  },
  {
    authorNum: 3,
    kind: 'offer',
    title: 'Лендинг под ключ для малого бизнеса',
    description: 'Tilda или Webflow, до 6 блоков, форма, Метрика/га при желании. Не «вау-арт», нормальный лендинг.',
    category: 'Design',
    tags: 'landing, web design, tilda, webflow',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 280000,
    daysAgo: 65,
  },
  {
    authorNum: 3,
    kind: 'offer',
    title: 'UI/UX редизайн мобильного приложения',
    description: 'До 20 экранов, Figma, флоу + UI-кит. Обычно две-три недели, если не летим в крайности.',
    category: 'Design',
    tags: 'ui, ux, figma, mobile',
    priceMode: 'negotiable',
    daysAgo: 28,
  },
  {
    authorNum: 3,
    kind: 'request',
    title: 'Нужен фотограф для портфолио на сайт',
    description:
      'Хочу снять 10–15 фото продуктов и пару портретов в студии. Алматы, ближайшие 2 недели.',
    category: 'Photography',
    tags: 'photo, portfolio, studio',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 60000,
    daysAgo: 6,
  },
  {
    authorNum: 4,
    kind: 'offer',
    title: 'Перевод документов KZ ↔ RU ↔ EN',
    description:
      'Дипломы, справки, контракты. Возможен нотариальный перевод. Срок 1–3 рабочих дня.',
    category: 'Translation',
    tags: 'translation, notary, kazakh, russian, english',
    city: 'Shymkent',
    priceMode: 'fixed',
    priceMin: 3500,
    daysAgo: 60,
  },
  {
    authorNum: 4,
    kind: 'offer',
    title: 'Устный перевод на встречах и переговорах',
    description: 'EN ↔ RU. Опыт сопровождения иностранных гостей и онлайн-звонков.',
    category: 'Translation',
    tags: 'interpreting, meetings, en, ru',
    priceMode: 'hourly',
    priceMin: 12000,
    priceMax: 18000,
    daysAgo: 19,
  },
  {
    authorNum: 5,
    kind: 'offer',
    title: 'IELTS preparation: academic & general',
    description:
      'Эссе на разбор, speaking по таймеру, раз в неделю сгоняем где вы просели. На C1 за полгода, если делать домашку.',
    category: 'Tutoring',
    tags: 'ielts, english, exam, online',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 9000,
    priceMax: 12000,
    daysAgo: 58,
  },
  {
    authorNum: 5,
    kind: 'offer',
    title: 'Conversational English, small group (3–4 people)',
    description:
      'Zoom, полтора часа, раз в неделю. Темы не из учебника. Пробное занятие бесплатно.',
    category: 'Tutoring',
    tags: 'english, speaking, group, zoom',
    priceMode: 'fixed',
    priceMin: 25000,
    daysAgo: 31,
  },
  {
    authorNum: 5,
    kind: 'request',
    title: 'Looking for a Spanish conversation partner',
    description: 'Somewhere A2/B1. 1–2 hrs/week. Can trade for English if you want.',
    category: 'Tutoring',
    tags: 'spanish, language exchange',
    priceMode: 'free',
    daysAgo: 3,
  },
  {
    authorNum: 6,
    kind: 'offer',
    title: 'Code review & mentorship for junior iOS devs',
    description:
      'До полутора часов в неделю. Смотрим PR, MVVM/TCA, что у вас горит по Swift.',
    category: 'Programming',
    tags: 'ios, swift, mentorship, code review',
    priceMode: 'hourly',
    priceMin: 18000,
    daysAgo: 50,
  },
  {
    authorNum: 6,
    kind: 'offer',
    title: 'Прототип iOS-приложения за 2 недели',
    description: 'SwiftUI + Supabase или Firebase. Норм для MVP, чтобы показать «вот оно крутится».',
    category: 'Programming',
    tags: 'ios, swiftui, mvp, prototype',
    priceMode: 'fixed',
    priceMin: 600000,
    daysAgo: 21,
    status: 'closed',
  },
  {
    authorNum: 6,
    kind: 'request',
    title: 'Нужен дизайнер для иконки приложения',
    description: 'Простая иконка, 2–3 варианта, светлая/тёмная. Бюджет до 30к.',
    category: 'Design',
    tags: 'icon, app icon',
    priceMode: 'fixed',
    priceMin: 30000,
    daysAgo: 8,
  },
  {
    authorNum: 7,
    kind: 'offer',
    title: 'Russian as a foreign language: A0 to B2',
    description:
      'Онлайн, подбираю материалы под человека, а не «курс для всех».',
    category: 'Tutoring',
    tags: 'russian, rfl, online, expats',
    priceMode: 'hourly',
    priceMin: 7000,
    priceMax: 9000,
    daysAgo: 56,
  },
  {
    authorNum: 8,
    kind: 'offer',
    title: 'Свадебная фотосъёмка, полный день',
    description: 'До 10 ч съёмки, отдаю 200+ обработанных. Репортаж + пара постановочных, без пластиковых улыбок по умолчанию.',
    category: 'Photography',
    tags: 'wedding, photography, full day',
    city: 'Karaganda',
    priceMode: 'fixed',
    priceMin: 250000,
    daysAgo: 54,
  },
  {
    authorNum: 8,
    kind: 'offer',
    title: 'Семейная фотосессия в студии',
    description: 'До 1.5 часов, 30 обработанных фото. Студия с реквизитом включена.',
    category: 'Photography',
    tags: 'family, studio, photo',
    city: 'Karaganda',
    priceMode: 'fixed',
    priceMin: 45000,
    daysAgo: 22,
  },
  {
    authorNum: 8,
    kind: 'offer',
    title: 'Предметная съёмка для маркетплейса',
    description: 'Kaspi/Wildberries. Белый фон, инфографика. От 30 фото. Сроки 2–4 дня.',
    category: 'Photography',
    tags: 'product, ecommerce, kaspi, wildberries',
    priceMode: 'fixed',
    priceMin: 1500,
    daysAgo: 11,
  },
  {
    authorNum: 9,
    kind: 'offer',
    title: 'Генеральная уборка квартиры (до 100 м²)',
    description: 'Команда из 2-х. ~5 часов работы, своя химия и инвентарь.',
    category: 'Cleaning',
    tags: 'deep clean, apartment, almaty',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 35000,
    daysAgo: 49,
  },
  {
    authorNum: 9,
    kind: 'offer',
    title: 'Поддерживающая уборка, раз в неделю',
    description: 'До 3-х часов. По договорённости: оплата за месяц.',
    category: 'Cleaning',
    tags: 'weekly, recurring',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 4000,
    daysAgo: 26,
  },
  {
    authorNum: 9,
    kind: 'offer',
    title: 'Уборка после ремонта',
    description: 'Снятие пыли, мойка окон и поверхностей, вывоз мусора по договорённости.',
    category: 'Cleaning',
    tags: 'post-renovation',
    city: 'Almaty',
    priceMode: 'negotiable',
    daysAgo: 5,
  },
  {
    authorNum: 10,
    kind: 'offer',
    title: 'Трансфер аэропорт Астана ↔ город',
    description: 'Toyota Camry 2022, встречаю с табличкой. Фиксированная цена в любое время.',
    category: 'Driving',
    tags: 'airport, transfer, astana',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 5000,
    daysAgo: 47,
  },
  {
    authorNum: 10,
    kind: 'offer',
    title: 'Личный водитель на день',
    description: 'До 8 часов или 100 км по городу. Бизнес-встречи, шопинг, экскурсии.',
    category: 'Driving',
    tags: 'driver, full day',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 35000,
    daysAgo: 17,
  },
  {
    authorNum: 11,
    kind: 'offer',
    title: 'Няня для детей 1–7 лет',
    description: 'Пед. образование, 8 лет опыта. Развивающие игры, чтение, прогулки.',
    category: 'Childcare',
    tags: 'nanny, children, almaty',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 3000,
    priceMax: 4000,
    daysAgo: 45,
  },
  {
    authorNum: 11,
    kind: 'offer',
    title: 'Няня на час, срочные выходы',
    description: 'Ребёнок от 2 лет. Минимум 3 часа, оплата по факту.',
    category: 'Childcare',
    tags: 'nanny, on-demand',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 4000,
    daysAgo: 18,
  },
  {
    authorNum: 12,
    kind: 'offer',
    title: 'Сайт под ключ для малого бизнеса',
    description:
      'Лендинг или каталог. Next.js, формы, аналитика, домен и хостинг помогу настроить.',
    category: 'Programming',
    tags: 'web, nextjs, landing, smb',
    priceMode: 'fixed',
    priceMin: 250000,
    priceMax: 600000,
    daysAgo: 43,
  },
  {
    authorNum: 12,
    kind: 'offer',
    title: 'Поддержка и доработки существующего сайта',
    description: 'Час работы: небольшие фичи, баги, обновления контента.',
    category: 'Programming',
    tags: 'support, maintenance',
    priceMode: 'hourly',
    priceMin: 12000,
    daysAgo: 13,
  },
  {
    authorNum: 13,
    kind: 'offer',
    title: 'Логотип + минимальный фирменный стиль',
    description: 'Логотип, 2–3 варианта, цветовая палитра, шрифты, исходники в AI/PDF.',
    category: 'Design',
    tags: 'logo, branding, identity',
    priceMode: 'fixed',
    priceMin: 120000,
    daysAgo: 40,
  },
  {
    authorNum: 13,
    kind: 'offer',
    title: 'Дизайн упаковки для локального бренда',
    description: 'От первого скетча до dieline. Опыт работы с пищёвкой и косметикой.',
    category: 'Design',
    tags: 'packaging, branding',
    priceMode: 'negotiable',
    daysAgo: 15,
  },
  {
    authorNum: 14,
    kind: 'offer',
    title: 'Квартирный переезд: Газель + 2 грузчика',
    description: 'Алматы и пригород. Минимум 3 часа. Своя упаковка по запросу.',
    category: 'Moving',
    tags: 'moving, gazelle, loaders',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 8000,
    daysAgo: 38,
  },
  {
    authorNum: 14,
    kind: 'offer',
    title: 'Офисный переезд под ключ',
    description: 'Разборка/сборка мебели, упаковка техники, опись.',
    category: 'Moving',
    tags: 'office, relocation',
    city: 'Almaty',
    priceMode: 'negotiable',
    daysAgo: 11,
  },
  {
    authorNum: 15,
    kind: 'offer',
    title: 'Қазақ тілі: балаларға және ересектерге',
    description: 'Бастапқы деңгейден сөйлеу деңгейіне дейін. Онлайн сабақтар, аптасына 2 рет.',
    category: 'Tutoring',
    tags: 'kazakh, online, language',
    priceMode: 'hourly',
    priceMin: 5000,
    priceMax: 7000,
    daysAgo: 36,
  },
  {
    authorNum: 15,
    kind: 'offer',
    title: 'Подготовка детей к школе на казахском',
    description: 'Чтение, письмо, счёт. Группы до 4-х детей. Актобе, очно или онлайн.',
    category: 'Tutoring',
    tags: 'school prep, kazakh, kids',
    city: 'Aktobe',
    priceMode: 'fixed',
    priceMin: 35000,
    daysAgo: 17,
  },
  {
    authorNum: 16,
    kind: 'offer',
    title: 'Уроки гитары: с нуля до своего первого костра',
    description: 'Акустика, классика, аккорды, бой, перебор. Первый урок бесплатно.',
    category: 'Music',
    tags: 'guitar, acoustic, beginners',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 7000,
    daysAgo: 34,
  },
  {
    authorNum: 16,
    kind: 'request',
    title: 'Ищу студию для записи акустического трека',
    description: 'Нужно записать 1 песню (вокал + гитара). 2–3 часа. Алматы, центр.',
    category: 'Music',
    tags: 'recording, studio, almaty',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 30000,
    daysAgo: 7,
  },
  {
    authorNum: 17,
    kind: 'offer',
    title: 'Yoga 1:1 sessions (Hatha & Vinyasa)',
    description: 'Ко мне в зал или домой. Час или полтора. Сертификат RYT-200 есть.',
    category: 'Fitness',
    tags: 'yoga, 1on1, astana',
    city: 'Astana',
    priceMode: 'hourly',
    priceMin: 12000,
    daysAgo: 32,
  },
  {
    authorNum: 17,
    kind: 'offer',
    title: 'Morning group yoga, outdoor (summer)',
    description: 'Вт/чт 7:30, парк в центре. Коврик с собой. Скидываетесь сколько не жалко.',
    category: 'Fitness',
    tags: 'yoga, group, outdoor',
    city: 'Astana',
    priceMode: 'free',
    daysAgo: 4,
  },
  {
    authorNum: 18,
    kind: 'offer',
    title: 'Диагностика и ТО автомобиля',
    description: 'Сканер, замена масла и фильтров. Подсказка что нужно и что подождёт.',
    category: 'Repair',
    tags: 'auto, mechanic, diagnostics',
    city: 'Karaganda',
    priceMode: 'fixed',
    priceMin: 12000,
    daysAgo: 30,
  },
  {
    authorNum: 18,
    kind: 'offer',
    title: 'Шиномонтаж: переобувка комплекта',
    description: 'Балансировка, накачка азотом, мойка дисков по запросу.',
    category: 'Repair',
    tags: 'tires, seasonal',
    city: 'Karaganda',
    priceMode: 'fixed',
    priceMin: 8000,
    daysAgo: 12,
  },
  {
    authorNum: 19,
    kind: 'offer',
    title: 'Передержка собак на выходные / отпуск',
    description: 'У меня дома (квартира с балконом), без других питомцев. Прогулки 3 раза в день.',
    category: 'Pet care',
    tags: 'dog, sitting, almaty',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 5000,
    daysAgo: 28,
    status: 'active',
  },
  {
    authorNum: 19,
    kind: 'offer',
    title: 'Выгул собак по будням',
    description: 'Утро или вечер, 45 мин. Отчёт фото/видео в Telegram.',
    category: 'Pet care',
    tags: 'dog walking',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 2500,
    daysAgo: 9,
  },
  {
    authorNum: 19,
    kind: 'request',
    title: 'Ищу ветеринара на дом: кошка, плановый осмотр',
    description: 'Нужны прививки и общая консультация. Можно вечером.',
    category: 'Pet care',
    tags: 'vet, cat, home visit',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 15000,
    daysAgo: 2,
  },
  {
    authorNum: 20,
    kind: 'offer',
    title: 'Шеф на дом: ужин на 4–8 человек',
    description: 'Меню из 4-х блюд, продукты привожу сам, всё готовлю на вашей кухне.',
    category: 'Cooking',
    tags: 'chef, dinner, private',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 80000,
    daysAgo: 27,
  },
  {
    authorNum: 20,
    kind: 'offer',
    title: 'Кейтеринг на небольшие мероприятия (до 30 человек)',
    description: 'Холодные/горячие закуски, основное, десерты. Приветственный аперитив.',
    category: 'Cooking',
    tags: 'catering, events',
    city: 'Almaty',
    priceMode: 'negotiable',
    daysAgo: 10,
  },
  {
    authorNum: 21,
    kind: 'offer',
    title: 'Подгонка одежды и мелкий ремонт',
    description: 'Подшить брюки, заменить молнию, ушить платье. Срок 1–3 дня.',
    category: 'Sewing',
    tags: 'alterations, repair',
    city: 'Shymkent',
    priceMode: 'fixed',
    priceMin: 1500,
    daysAgo: 25,
  },
  {
    authorNum: 21,
    kind: 'offer',
    title: 'Пошив штор и постельного белья на заказ',
    description: 'Замер, ткань на выбор, доставка по городу.',
    category: 'Sewing',
    tags: 'curtains, bedding, custom',
    city: 'Shymkent',
    priceMode: 'negotiable',
    daysAgo: 7,
  },
  {
    authorNum: 22,
    kind: 'offer',
    title: 'Регистрация ТОО / ИП под ключ',
    description: 'Все документы, открытие счёта, консультация по налогам. Срок 3–5 рабочих дней.',
    category: 'Legal',
    tags: 'company, registration, llp',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 60000,
    daysAgo: 24,
  },
  {
    authorNum: 22,
    kind: 'offer',
    title: 'Юридическая консультация, 1 час',
    description: 'Договоры, споры, трудовое право. Первая встреча бесплатно (30 мин).',
    category: 'Legal',
    tags: 'consultation, contracts',
    city: 'Astana',
    priceMode: 'hourly',
    priceMin: 25000,
    daysAgo: 8,
  },
  {
    authorNum: 23,
    kind: 'offer',
    title: 'Бухгалтерское сопровождение ИП',
    description: 'Ежемесячная отчётность, общение с налоговой, кадры. От 1500 операций, отдельно.',
    category: 'Accounting',
    tags: 'accounting, ip, monthly',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 35000,
    daysAgo: 23,
  },
  {
    authorNum: 23,
    kind: 'offer',
    title: 'Сдам отчёт за вас за один день',
    description: 'Срочные ситуации, штрафы, разовые отчёты. Без долгого договора.',
    category: 'Accounting',
    tags: 'urgent, report, smb',
    priceMode: 'fixed',
    priceMin: 15000,
    daysAgo: 6,
  },
  {
    authorNum: 24,
    kind: 'offer',
    title: 'Чистка ноутбука + замена термопасты',
    description: 'Снижу температуру и шум. Гарантия 3 месяца. Алматы, выезд по городу +1500.',
    category: 'Repair',
    tags: 'laptop, cleaning, thermal paste',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 9000,
    daysAgo: 21,
  },
  {
    authorNum: 24,
    kind: 'offer',
    title: 'Установка Windows / macOS + софт',
    description: 'Настройка с нуля, перенос данных, установка нужных программ.',
    category: 'Repair',
    tags: 'os install, setup',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 7000,
    daysAgo: 4,
  },
  {
    authorNum: 25,
    kind: 'offer',
    title: 'Стрижка и укладка на дому',
    description: 'Привезу всё с собой. Удобно для мам и тех, кто не хочет в салон.',
    category: 'Beauty',
    tags: 'haircut, home, astana',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 12000,
    daysAgo: 19,
  },
  {
    authorNum: 25,
    kind: 'offer',
    title: 'Окрашивание волос, выезд на дом',
    description: 'Крем-краска L’Oréal/Schwarzkopf, тонирование, омбре. Цена зависит от длины.',
    category: 'Beauty',
    tags: 'color, hair',
    city: 'Astana',
    priceMode: 'negotiable',
    daysAgo: 5,
  },
  {
    authorNum: 26,
    kind: 'offer',
    title: 'Personal training: 8 sessions / month',
    description: 'Сила + чуть гибкости, раз в неделю спрашиваю «как оно». Про еду, базово. Залы в Алмате.',
    category: 'Fitness',
    tags: 'pt, strength, mobility',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 90000,
    daysAgo: 17,
  },
  {
    authorNum: 26,
    kind: 'offer',
    title: 'Outdoor bootcamp, Saturdays at Kok-Tobe',
    description: 'Час, кто угодно по уровню. Вода с собой, друга можно. Первый раз бесплатно.',
    category: 'Fitness',
    tags: 'bootcamp, outdoor, group',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 4000,
    daysAgo: 3,
  },
  {
    authorNum: 27,
    kind: 'offer',
    title: 'Организация дня рождения «под ключ»',
    description: 'Ведущий, декор, торт, фото/видео на ваш бюджет.',
    category: 'Events',
    tags: 'birthday, planning',
    city: 'Astana',
    priceMode: 'negotiable',
    daysAgo: 15,
  },
  {
    authorNum: 27,
    kind: 'offer',
    title: 'Декор для свадьбы / тоя',
    description: 'Президиумы, арки, свет, текстиль. Срок 7–10 дней до мероприятия.',
    category: 'Events',
    tags: 'wedding, decor, toi',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 350000,
    daysAgo: 6,
  },
  {
    authorNum: 28,
    kind: 'offer',
    title: 'Сборка мебели IKEA / Hoff',
    description: 'Шкафы, кровати, кухни. Свой инструмент. Выезд по Алматы.',
    category: 'Handyman',
    tags: 'furniture, ikea, assembly',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 6000,
    daysAgo: 13,
  },
  {
    authorNum: 28,
    kind: 'offer',
    title: 'Установка карнизов, полок, телевизоров на стену',
    description: 'Минимум 1 час. Кронштейн могу привезти.',
    category: 'Handyman',
    tags: 'install, mount',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 4500,
    daysAgo: 4,
  },
  {
    authorNum: 29,
    kind: 'offer',
    title: 'Стикерпак для Telegram / WhatsApp',
    description: 'До 12 стикеров в едином стиле. 2 правки в комплекте.',
    category: 'Design',
    tags: 'stickers, telegram, illustration',
    priceMode: 'fixed',
    priceMin: 35000,
    daysAgo: 11,
  },
  {
    authorNum: 29,
    kind: 'offer',
    title: 'Иллюстрация на заказ: портрет, аватарка',
    description: 'Цифровая иллюстрация, формат под печать или соцсети.',
    category: 'Design',
    tags: 'illustration, portrait',
    priceMode: 'fixed',
    priceMin: 15000,
    daysAgo: 2,
  },
  {
    authorNum: 30,
    kind: 'request',
    title: 'Ищу репетитора по химии (8–11 класс)',
    description: 'Готовлюсь к олимпиаде. Желательно онлайн, 2 раза в неделю.',
    category: 'Tutoring',
    tags: 'chemistry, olympiad, online',
    priceMode: 'hourly',
    priceMin: 5000,
    priceMax: 8000,
    daysAgo: 9,
  },
  {
    authorNum: 30,
    kind: 'offer',
    title: 'Курьерские задачи по Астане, пешком/метро',
    description: 'Передам документы, заберу заказ. Гибкое расписание у студента.',
    category: 'Driving',
    tags: 'courier, errands, astana',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 1500,
    daysAgo: 5,
  },
  {
    authorNum: 4,
    kind: 'request',
    title: 'Нужна уборка квартиры перед сдачей',
    description: 'Двушка 60 м², в Шымкенте. На этой неделе.',
    category: 'Cleaning',
    tags: 'cleaning, shymkent',
    city: 'Shymkent',
    priceMode: 'fixed',
    priceMin: 25000,
    daysAgo: 4,
  },
  {
    authorNum: 7,
    kind: 'request',
    title: 'Need a logo for a small Russian-tutoring brand',
    description: 'Надпись + простая иконка, две правки входят. Около 120к, если не упрёмся в правки №17.',
    category: 'Design',
    tags: 'logo, branding',
    priceMode: 'fixed',
    priceMin: 120000,
    daysAgo: 12,
    status: 'closed',
  },
  {
    authorNum: 17,
    kind: 'request',
    title: 'Looking for a photographer: yoga retreat (1 day)',
    description: 'Улица + зал в ретрите, ~80 фото в обработке. Июнь, даты скажу в личке.',
    category: 'Photography',
    tags: 'photo, retreat, yoga',
    priceMode: 'fixed',
    priceMin: 120000,
    daysAgo: 8,
  },
  {
    authorNum: 22,
    kind: 'request',
    title: 'Ищу бухгалтера для нового ТОО (IT-сфера)',
    description: 'Есть учредители, ОКЭД готов. Нужен ежемесячный аутсорс.',
    category: 'Accounting',
    tags: 'accounting, llp, it',
    city: 'Astana',
    priceMode: 'negotiable',
    daysAgo: 6,
  },
  {
    authorNum: 26,
    kind: 'request',
    title: 'Need a nutritionist: meal plan for cutting',
    description: 'План на 6 недель, раз в неделю отпишемся как идёт. Халяль продукты могу заложить.',
    category: 'Fitness',
    tags: 'nutrition, plan, cutting',
    priceMode: 'fixed',
    priceMin: 40000,
    daysAgo: 3,
  },
  {
    authorNum: 12,
    kind: 'request',
    title: 'Ищу копирайтера для лендинга на казахском',
    description: 'Сервис доставки, ~1500 знаков. Срок 1 неделя.',
    category: 'Translation',
    tags: 'copywriting, kazakh, landing',
    priceMode: 'fixed',
    priceMin: 50000,
    daysAgo: 5,
  },
  {
    authorNum: 28,
    kind: 'offer',
    title: 'Перевозка холодильника / стиралки, 1 ездка',
    description: 'С грузчиками. По Алматы и пригороду до 30 км.',
    category: 'Moving',
    tags: 'appliance, single trip',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 12000,
    daysAgo: 16,
  },
  {
    authorNum: 14,
    kind: 'offer',
    title: 'Помощь на переезде: 2 грузчика, без машины',
    description: 'Час работы. Удобно если своя машина уже есть.',
    category: 'Moving',
    tags: 'loaders, hourly',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 5000,
    daysAgo: 25,
    status: 'closed',
  },
  {
    authorNum: 19,
    kind: 'offer',
    title: 'Передержка кошки на время отпуска',
    description: 'У меня дома, отдельная комната. Фото и отчёты ежедневно.',
    category: 'Pet care',
    tags: 'cat, sitting',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 3500,
    daysAgo: 7,
  },
  {
    authorNum: 30,
    kind: 'offer',
    title: 'Помогу настроить смартфон родителям / бабушке',
    description: 'Соцсети, Каспи, Telegram, шрифт покрупнее. Объясню понятно.',
    category: 'Repair',
    tags: 'smartphone, elderly, setup',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 5000,
    daysAgo: 3,
  },
  {
    authorNum: 11,
    kind: 'request',
    title: 'Ищу детского психолога, консультация',
    description: 'Дочке 5 лет, проблемы со сном. Готова на онлайн.',
    category: 'Tutoring',
    tags: 'psychology, kids',
    priceMode: 'hourly',
    priceMin: 12000,
    daysAgo: 11,
  },
  {
    authorNum: 5,
    kind: 'request',
    title: 'Help me build a personal portfolio site',
    description: 'Одна страница, штук пять блоков, весь текст на EN. Tilda или Framer, мне без разницы.',
    category: 'Programming',
    tags: 'portfolio, web',
    priceMode: 'fixed',
    priceMin: 80000,
    daysAgo: 4,
  },
  {
    authorNum: 8,
    kind: 'request',
    title: 'Нужен ассистент на свадебную съёмку (1 день)',
    description: 'Помогать со светом, переноской, второй камерой. Караганда.',
    category: 'Photography',
    tags: 'assistant, wedding',
    city: 'Karaganda',
    priceMode: 'fixed',
    priceMin: 25000,
    daysAgo: 9,
  },
  {
    authorNum: 27,
    kind: 'offer',
    title: 'Аренда фотозоны и оформление шаров',
    description: 'Подача в день мероприятия. Оформление под цвет вашей темы.',
    category: 'Events',
    tags: 'balloons, decor',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 45000,
    daysAgo: 14,
  },
  {
    authorNum: 21,
    kind: 'offer',
    title: 'Пошив национальной одежды на заказ',
    description: 'Камзол, чапан, платья. Замеры и согласование ткани.',
    category: 'Sewing',
    tags: 'kazakh, national, custom',
    city: 'Shymkent',
    priceMode: 'negotiable',
    daysAgo: 5,
  },
  {
    authorNum: 16,
    kind: 'offer',
    title: 'Уроки укулеле для детей 7+',
    description: 'Весело, без скучной теории. Первые 3 песни за 4 урока.',
    category: 'Music',
    tags: 'ukulele, kids',
    city: 'Almaty',
    priceMode: 'hourly',
    priceMin: 5000,
    daysAgo: 6,
  },
  {
    authorNum: 25,
    kind: 'request',
    title: 'Ищу маникюр на дому, раз в 3 недели',
    description: 'Покрытие гель-лак, аккуратно. Левый берег Астаны.',
    category: 'Beauty',
    tags: 'manicure, home',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 8000,
    daysAgo: 2,
  },
  {
    authorNum: 24,
    kind: 'request',
    title: 'Нужны курсы Excel, продвинутый уровень',
    description: 'Сводные таблицы, Power Query, базовый VBA. 8 занятий.',
    category: 'Tutoring',
    tags: 'excel, advanced',
    priceMode: 'fixed',
    priceMin: 60000,
    daysAgo: 4,
  },
  {
    authorNum: 6,
    kind: 'offer',
    title: 'Tech interview prep: Swift & system design',
    description: 'Собесы «как на реале», разбор кода, шпаргалка что добить. Пакет из 4 встреч.',
    category: 'Programming',
    tags: 'interview, swift, mentorship',
    priceMode: 'fixed',
    priceMin: 80000,
    daysAgo: 1,
  },
  {
    authorNum: 9,
    kind: 'request',
    title: 'Ищу мойщика окон в высотке',
    description: '12 этаж, панорамные. Нужно один раз перед фотосессией.',
    category: 'Cleaning',
    tags: 'windows, high-rise',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 18000,
    daysAgo: 8,
  },
  {
    authorNum: 13,
    kind: 'offer',
    title: 'Дизайн презентации для инвесторов (pitch deck)',
    description: 'До 15 слайдов, в едином стиле, графика. Срок 5 рабочих дней.',
    category: 'Design',
    tags: 'pitch, presentation',
    priceMode: 'fixed',
    priceMin: 90000,
    daysAgo: 22,
  },
  {
    authorNum: 18,
    kind: 'request',
    title: 'Нужен автоэлектрик: Toyota Corolla 2014',
    description: 'Не открывается центральный замок, иногда. Караганда.',
    category: 'Repair',
    tags: 'auto, electrician, toyota',
    city: 'Karaganda',
    priceMode: 'fixed',
    priceMin: 8000,
    daysAgo: 5,
  },
  {
    authorNum: 20,
    kind: 'offer',
    title: 'Готовые домашние обеды на неделю, 5 дней',
    description: 'Полезно, без заморозки. Доставка по центру Алматы.',
    category: 'Cooking',
    tags: 'meal prep, weekly, almaty',
    city: 'Almaty',
    priceMode: 'fixed',
    priceMin: 22000,
    daysAgo: 9,
  },
  {
    authorNum: 23,
    kind: 'request',
    title: 'Ищу аудитора для ТОО, small scope',
    description: 'Внутренний аудит за прошлый год. 2–3 дня работы.',
    category: 'Accounting',
    tags: 'audit, llp',
    priceMode: 'negotiable',
    daysAgo: 11,
  },
  {
    authorNum: 10,
    kind: 'offer',
    title: 'Поездка в Боровое / Бурабай, день туда-обратно',
    description: 'Минивэн до 6 человек. Маршрут на ваш выбор.',
    category: 'Driving',
    tags: 'borovoye, trip, minivan',
    city: 'Astana',
    priceMode: 'fixed',
    priceMin: 65000,
    daysAgo: 2,
  },
  {
    authorNum: 15,
    kind: 'offer',
    title: 'Помощь с домашним заданием на казахском (1–4 класс)',
    description: 'Чтение, окружающий мир, математика. По Skype. 2 раза в неделю.',
    category: 'Tutoring',
    tags: 'homework, kazakh, primary',
    priceMode: 'hourly',
    priceMin: 4000,
    daysAgo: 4,
  },
  {
    authorNum: 3,
    kind: 'offer',
    title: 'Гостевые посты и обложки для Instagram (10 шт.)',
    description: 'Один стиль на десять постов + обложка под reels, в цене.',
    category: 'Design',
    tags: 'instagram, smm, posts',
    priceMode: 'fixed',
    priceMin: 50000,
    daysAgo: 1,
  },
  {
    authorNum: 2,
    kind: 'offer',
    title: 'Бесплатная консультация по затоплению (исключено модератором)',
    description: 'Removed by moderation example.',
    category: 'Repair',
    tags: 'free',
    priceMode: 'free',
    daysAgo: 33,
    status: 'hidden',
  },
];
type SeedEngagement = {
  num: number;
  listingNum: number;
  counterpartNum: number;
  daysAgo: number;
  completedDaysAgo?: number;
  reviews?: SeedReview[];
};
type SeedReview = {
  by: 'owner' | 'counterpart';
  rating: number;
  text?: string | null;
  daysAgo: number;
};
const ENGAGEMENTS: SeedEngagement[] = [
  {
    num: 1,
    listingNum: 1,
    counterpartNum: 30,
    daysAgo: 60,
    completedDaysAgo: 30,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Год полтора возились с матешой. На ЕНТ вышло 38 из 40, я доволен.',
        daysAgo: 28,
      },
      {
        by: 'owner',
        rating: 5,
        text: 'Илияс ответственный, всегда делал домашку. Желаю удачи в универе!',
        daysAgo: 27,
      },
    ],
  },
  {
    num: 2,
    listingNum: 4,
    counterpartNum: 5,
    daysAgo: 55,
    completedDaysAgo: 54,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Приехал в течение часа, всё починил быстро. Цена адекватная.',
        daysAgo: 54,
      },
    ],
  },
  {
    num: 3,
    listingNum: 8,
    counterpartNum: 6,
    daysAgo: 26,
    completedDaysAgo: 4,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Прототип даже лучше наброска был. По отступам и шрифтам заморочилась как надо.',
        daysAgo: 3,
      },
      {
        by: 'owner',
        rating: 5,
        text: 'Санжар чётко формулирует требования, приятно работать.',
        daysAgo: 2,
      },
    ],
  },
  {
    num: 4,
    listingNum: 10,
    counterpartNum: 22,
    daysAgo: 50,
    completedDaysAgo: 47,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Перевод документов был готов за один день, нотариус принял без вопросов.',
        daysAgo: 46,
      },
      {
        by: 'owner',
        rating: 5,
        text: 'Марат, внимательный клиент, всё чётко по делу.',
        daysAgo: 46,
      },
    ],
  },
  {
    num: 5,
    listingNum: 12,
    counterpartNum: 19,
    daysAgo: 50,
    completedDaysAgo: 12,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'IELTS 7.5. У Алии долго и много пишем, но по грамматике реально подтянула.',
        daysAgo: 11,
      },
    ],
  },
  {
    num: 6,
    listingNum: 15,
    counterpartNum: 12,
    daysAgo: 40,
    completedDaysAgo: 7,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Разборы PR норм, не просто «молодец». После четырёх встреч с архитектурой полегче стало.',
        daysAgo: 6,
      },
    ],
  },
  {
    num: 7,
    listingNum: 16,
    counterpartNum: 27,
    daysAgo: 21,
    completedDaysAgo: 5,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Рабочий прототип за 12 дней, даже раньше чем ждали.',
        daysAgo: 4,
      },
      {
        by: 'owner',
        rating: 5,
        text: 'Айжан с ТЗ не расплывалась, ответы в тот же день. Работать можно.',
        daysAgo: 4,
      },
    ],
  },
  {
    num: 8,
    listingNum: 18,
    counterpartNum: 17,
    daysAgo: 45,
    completedDaysAgo: 20,
    reviews: [
      {
        by: 'counterpart',
        rating: 4,
        text: 'Grammar drills fine, wanted a bit more free talk. Still worth it.',
        daysAgo: 18,
      },
    ],
  },
  {
    num: 9,
    listingNum: 19,
    counterpartNum: 27,
    daysAgo: 45,
    completedDaysAgo: 30,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'На свадьбе всё в кадр попало, тёток из танцев не забыли. Фото через две недели.',
        daysAgo: 27,
      },
      {
        by: 'owner',
        rating: 5,
        text: 'С организацией тихо, без «ой забыл». За день ни одной паники.',
        daysAgo: 27,
      },
    ],
  },
  {
    num: 10,
    listingNum: 20,
    counterpartNum: 11,
    daysAgo: 18,
    completedDaysAgo: 14,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Дети не ныли, фото без слез в глазах у бабушки, редкость.',
        daysAgo: 13,
      },
    ],
  },
  {
    num: 11,
    listingNum: 22,
    counterpartNum: 12,
    daysAgo: 40,
    completedDaysAgo: 39,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'После них квартира как новая. Заберу в постоянку.',
        daysAgo: 38,
      },
    ],
  },
  {
    num: 12,
    listingNum: 23,
    counterpartNum: 6,
    daysAgo: 22,
    completedDaysAgo: 1,
    reviews: [
      {
        by: 'counterpart',
        rating: 4,
        text: 'Стабильное качество, иногда задерживаются на 15–20 минут.',
        daysAgo: 1,
      },
    ],
  },
  {
    num: 13,
    listingNum: 25,
    counterpartNum: 22,
    daysAgo: 30,
    completedDaysAgo: 29,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Чисто, вовремя, спокойный водитель. Буду заказывать ещё.',
        daysAgo: 28,
      },
    ],
  },
  {
    num: 14,
    listingNum: 27,
    counterpartNum: 1,
    daysAgo: 14,
    completedDaysAgo: 1,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Анель сразу нашла подход к ребёнку. Спасибо большое!',
        daysAgo: 1,
      },
      {
        by: 'owner',
        rating: 5,
        text: 'Аигерим заботливая мама, было приятно работать.',
        daysAgo: 1,
      },
    ],
  },
  {
    num: 15,
    listingNum: 29,
    counterpartNum: 25,
    daysAgo: 35,
    completedDaysAgo: 10,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Сделал сайт точно как договаривались. Объяснял всё простым языком.',
        daysAgo: 9,
      },
    ],
  },
  {
    num: 16,
    listingNum: 31,
    counterpartNum: 27,
    daysAgo: 35,
    completedDaysAgo: 25,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Три варианта на выбор, не мучили нас десятью правками. Один понравился сразу.',
        daysAgo: 23,
      },
    ],
  },
  {
    num: 17,
    listingNum: 33,
    counterpartNum: 5,
    daysAgo: 28,
    completedDaysAgo: 27,
    reviews: [
      {
        by: 'counterpart',
        rating: 4,
        text: 'Аккуратные ребята, но опоздали на 1.5 часа из-за пробок.',
        daysAgo: 26,
      },
    ],
  },
  {
    num: 18,
    listingNum: 35,
    counterpartNum: 17,
    daysAgo: 30,
    completedDaysAgo: 6,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'С Зариной хоть в магазине казахским заговорила. Без понтов, по делу.',
        daysAgo: 5,
      },
    ],
  },
  {
    num: 19,
    listingNum: 37,
    counterpartNum: 6,
    daysAgo: 32,
    completedDaysAgo: 0,
  },
  {
    num: 20,
    listingNum: 39,
    counterpartNum: 7,
    daysAgo: 28,
    completedDaysAgo: 4,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Скинул что спина болит, поменяли упоры. После трёх раз легче стало подниматься.',
        daysAgo: 3,
      },
    ],
  },
  {
    num: 21,
    listingNum: 41,
    counterpartNum: 10,
    daysAgo: 25,
    completedDaysAgo: 24,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Честный диагноз, сделал только то что нужно. Цена как договаривались.',
        daysAgo: 23,
      },
    ],
  },
  {
    num: 22,
    listingNum: 44,
    counterpartNum: 20,
    daysAgo: 25,
    completedDaysAgo: 18,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Каждый день фото и видео. Собака вернулась довольной и спокойной.',
        daysAgo: 17,
      },
    ],
  },
  {
    num: 23,
    listingNum: 45,
    counterpartNum: 9,
    daysAgo: 9,
    completedDaysAgo: 2,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Очень ответственная. Собака теперь сама идёт к двери, когда видит Анну.',
        daysAgo: 1,
      },
    ],
  },
  {
    num: 24,
    listingNum: 47,
    counterpartNum: 13,
    daysAgo: 24,
    completedDaysAgo: 22,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Гости до сих пор вспоминают стол. Олжас с продуктами сам заморочился.',
        daysAgo: 21,
      },
    ],
  },
  {
    num: 25,
    listingNum: 49,
    counterpartNum: 25,
    daysAgo: 22,
    completedDaysAgo: 21,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Платье село идеально. Всё за один день.',
        daysAgo: 20,
      },
    ],
  },
  {
    num: 26,
    listingNum: 51,
    counterpartNum: 23,
    daysAgo: 21,
    completedDaysAgo: 14,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'ТОО зарегали за 4 дня, без беготни по кабинетам. По юристу норм.',
        daysAgo: 13,
      },
      {
        by: 'owner',
        rating: 5,
        text: 'Айман бухгалтером норм, если кому надо, скажу контакт.',
        daysAgo: 12,
      },
    ],
  },
  {
    num: 27,
    listingNum: 53,
    counterpartNum: 28,
    daysAgo: 20,
    completedDaysAgo: 0,
  },
  {
    num: 28,
    listingNum: 55,
    counterpartNum: 29,
    daysAgo: 20,
    completedDaysAgo: 19,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Ноутбук перестал гудеть. Цена адекватная, всё прозрачно.',
        daysAgo: 18,
      },
    ],
  },
  {
    num: 29,
    listingNum: 57,
    counterpartNum: 17,
    daysAgo: 17,
    completedDaysAgo: 16,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Сделала причёску быстрее чем в салоне и в 1.5 раза дешевле.',
        daysAgo: 15,
      },
    ],
  },
  {
    num: 30,
    listingNum: 59,
    counterpartNum: 20,
    daysAgo: 16,
    completedDaysAgo: 0,
  },
  {
    num: 31,
    listingNum: 61,
    counterpartNum: 11,
    daysAgo: 14,
    completedDaysAgo: 7,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Дочке понравилось, клоуна до сих пор называет по имени.',
        daysAgo: 6,
      },
    ],
  },
  {
    num: 32,
    listingNum: 63,
    counterpartNum: 5,
    daysAgo: 12,
    completedDaysAgo: 11,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Собрал всё ровно, ничего не сломал. Цена честная.',
        daysAgo: 10,
      },
    ],
  },
  {
    num: 33,
    listingNum: 65,
    counterpartNum: 6,
    daysAgo: 10,
    completedDaysAgo: 2,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Стикеры огонь, друзья просят такие же сделать им.',
        daysAgo: 1,
      },
    ],
  },
  {
    num: 34,
    listingNum: 34,
    counterpartNum: 22,
    daysAgo: 11,
    completedDaysAgo: 10,
    reviews: [
      {
        by: 'counterpart',
        rating: 4,
        text: 'Перевезли быстро, но один монитор поцарапали. Возместили без споров.',
        daysAgo: 9,
      },
    ],
  },
  {
    num: 35,
    listingNum: 11,
    counterpartNum: 5,
    daysAgo: 18,
    completedDaysAgo: 17,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Ержан справку для IELTS перевёл в тот же день, очень выручил.',
        daysAgo: 16,
      },
    ],
  },
  {
    num: 36,
    listingNum: 42,
    counterpartNum: 27,
    daysAgo: 12,
    completedDaysAgo: 11,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Чисто, без сюрпризов по времени, чай нормальный. Была ещё раз.',
        daysAgo: 10,
      },
    ],
  },
  { num: 37, listingNum: 2, counterpartNum: 28, daysAgo: 6 },
  { num: 38, listingNum: 6, counterpartNum: 14, daysAgo: 5 },
  { num: 39, listingNum: 13, counterpartNum: 30, daysAgo: 4 },
  { num: 40, listingNum: 24, counterpartNum: 20, daysAgo: 3 },
  { num: 41, listingNum: 28, counterpartNum: 7, daysAgo: 2 },
  {
    num: 42,
    listingNum: 50,
    counterpartNum: 13,
    daysAgo: 12,
    completedDaysAgo: 8,
    reviews: [
      {
        by: 'counterpart',
        rating: 3,
        text: 'Шторы шили дольше обещанного, но качество хорошее.',
        daysAgo: 7,
      },
    ],
  },
  {
    num: 43,
    listingNum: 56,
    counterpartNum: 30,
    daysAgo: 8,
    completedDaysAgo: 6,
    reviews: [
      {
        by: 'counterpart',
        rating: 2,
        text: 'Установили macOS, но программы поставили не те, что просил. Пришлось переделывать.',
        daysAgo: 5,
      },
    ],
  },
  {
    num: 44,
    listingNum: 36,
    counterpartNum: 11,
    daysAgo: 14,
    completedDaysAgo: 9,
    reviews: [
      {
        by: 'counterpart',
        rating: 5,
        text: 'Дети к школе пришли уверенно, читают и считают. Огромное спасибо!',
        daysAgo: 8,
      },
    ],
  },
];
function userId(num: number): string {
  return `seed_user_${pad(num)}`;
}
function listingId(num: number): string {
  return `seed_listing_${pad(num, 4)}`;
}
function engagementId(num: number): string {
  return `seed_eng_${pad(num, 4)}`;
}
function reviewId(engNum: number, idx: number): string {
  return `seed_rev_${pad(engNum, 4)}_${idx}`;
}
const out: string[] = [];
out.push('-- Komektes seed data');
out.push('-- Generated by scripts/seed.ts. Re-running is safe (INSERT OR IGNORE).');
out.push('');
out.push('PRAGMA defer_foreign_keys = ON;');
out.push('');
out.push('-- Users');
for (const u of PEOPLE) {
  const created = NOW - u.joinedDaysAgo * DAY;
  out.push(
    `INSERT OR IGNORE INTO user (id, name, email, email_verified, image, created_at, updated_at) VALUES (${[
      sq(userId(u.num)),
      sq(u.name),
      sq(u.email),
      1,
      sq(u.image ?? null),
      created,
      created,
    ].join(', ')});`,
  );
}
out.push('');
out.push('-- Profiles');
for (const u of PEOPLE) {
  const created = NOW - u.joinedDaysAgo * DAY + HOUR;
  out.push(
    `INSERT OR IGNORE INTO profile (id, display_name, telegram, city, bio, created_at, updated_at) VALUES (${[
      sq(userId(u.num)),
      sq(u.displayName),
      sq(u.telegram),
      sq(u.city),
      sq(u.bio),
      created,
      created,
    ].join(', ')});`,
  );
}
out.push('');
out.push('-- Listings');
LISTINGS.forEach((l, i) => {
  const num = i + 1;
  const created = NOW - l.daysAgo * DAY + rint(0, 12) * HOUR;
  const updated = created + rint(0, 24) * HOUR;
  const currency = l.currency ?? 'KZT';
  const summary = buildPriceSummary(l.priceMode, l.priceMin, l.priceMax, currency);
  out.push(
    `INSERT OR IGNORE INTO listing (id, author_id, kind, title, description, category, tags, city, price_mode, price_min, price_max, currency, price_summary, status, created_at, updated_at) VALUES (${[
      sq(listingId(num)),
      sq(userId(l.authorNum)),
      sq(l.kind),
      sq(l.title),
      sq(l.description),
      sq(l.category),
      sq(l.tags),
      sq(l.city ?? null),
      sq(l.priceMode),
      l.priceMin ?? 'NULL',
      l.priceMax ?? 'NULL',
      sq(currency),
      sq(summary ?? null),
      sq(l.status ?? 'active'),
      created,
      updated,
    ].join(', ')});`,
  );
});
out.push('');
out.push('-- Engagements');
for (const e of ENGAGEMENTS) {
  const created = NOW - e.daysAgo * DAY + rint(0, 12) * HOUR;
  const completedAt =
    e.completedDaysAgo !== undefined ? NOW - e.completedDaysAgo * DAY + rint(0, 8) * HOUR : null;
  const lst = LISTINGS[e.listingNum - 1];
  if (!lst) {
    throw new Error(`Engagement ${e.num} references unknown listing ${e.listingNum}`);
  }
  out.push(
    `INSERT OR IGNORE INTO engagement (id, listing_id, owner_id, counterpart_id, completed_at, created_at) VALUES (${[
      sq(engagementId(e.num)),
      sq(listingId(e.listingNum)),
      sq(userId(lst.authorNum)),
      sq(userId(e.counterpartNum)),
      completedAt ?? 'NULL',
      created,
    ].join(', ')});`,
  );
}
out.push('');
out.push('-- Reviews');
for (const e of ENGAGEMENTS) {
  if (!e.reviews || e.reviews.length === 0) continue;
  const lst = LISTINGS[e.listingNum - 1];
  e.reviews.forEach((r, idx) => {
    const authorNum = r.by === 'owner' ? lst.authorNum : e.counterpartNum;
    const subjectNum = r.by === 'owner' ? e.counterpartNum : lst.authorNum;
    const created = NOW - r.daysAgo * DAY + rint(0, 12) * HOUR;
    out.push(
      `INSERT OR IGNORE INTO review (id, engagement_id, author_id, subject_id, rating, text, created_at) VALUES (${[
        sq(reviewId(e.num, idx)),
        sq(engagementId(e.num)),
        sq(userId(authorNum)),
        sq(userId(subjectNum)),
        r.rating,
        sq(r.text ?? null),
        created,
      ].join(', ')});`,
    );
  });
}
out.push('');
out.push(
  `-- Counts: users=${PEOPLE.length}, listings=${LISTINGS.length}, engagements=${ENGAGEMENTS.length}, reviews=${ENGAGEMENTS.reduce((acc, e) => acc + (e.reviews?.length ?? 0), 0)}`,
);
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out.join('\n') + '\n', 'utf-8');
const reviewCount = ENGAGEMENTS.reduce((a, e) => a + (e.reviews?.length ?? 0), 0);
console.log(
  `Wrote ${OUT}\n  • ${PEOPLE.length} users (+ profiles)\n  • ${LISTINGS.length} listings\n  • ${ENGAGEMENTS.length} engagements\n  • ${reviewCount} reviews`,
);
void _rng;
void chance;
void pick;
void CITIES;
